services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=in3omnia
      - POSTGRES_DB=movie-recommendations-api

  your-service:
    image: openjdk:latest
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=in3omnia
      - DB_NAME=movie-recommendations-api

volumes:
  postgres_data:
